
channels:
- conda-forge
dependencies:
- python=3.6.2
- pip:
#   - azureml-core==1.18.0.post1
#   - azureml-defaults==1.18.0
  - azureml-defaults
  - torch==1.6.0
  - torchvision==0.7.0
  - future==0.17.1
  - pillow
